version: "3"

services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432"

  web: &app
    build:
      context: .
      args:
        BUNDLE_WITH: development test
        YARN_PRODUCTION: "false"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

volumes:
  bundle:
  node_modules:
